FROM node:16-alpine

# Set the work directory to backend folder
WORKDIR /app

# Copy package.json file in the app folder inside container
COPY package*.json .

# Install the dependencies in the container
RUN npm install

# Copy the rest of the code in the container
COPY . .

# Expose the service over PORT 3000 (React)
EXPOSE 3000

# Start React app in Dev mode
CMD ["npm", "run", "start"]