FROM node:alpine

# Set the work directory to backend folder
WORKDIR /app

# Copy package.json file in the app folder inside container
COPY package*.json .

# Install the dependencies in the container
RUN npm install

# Copy the rest of the code in the container
COPY . .

# Run the build command
RUN npm run start